import Head from 'next/head';
import Image from 'next/image';
import { Button } from '@mui/material';
import { useState } from 'react';

const Home = () => {
  return (
    <>
      <Head>
        <title>받아쓰기</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};
export default Home;
