import Head from 'next/head';
import {
  BottomNavigation,
  BottomNavigationAction,
  Box,
  Paper,
} from '@mui/material';
import Ranking from '../src/components/Ranking';
import RestoreIcon from '@mui/icons-material/Restore';
import FavoriteIcon from '@mui/icons-material/Favorite';
import LocationOnIcon from '@mui/icons-material/LocationOn';

const RankingPage = () => {
  return (
    <>
      <Head>
        <title>받아쓰기</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ position: 'relative', maxWidth: 360 }}>
        <Box mt="50px" pl={3} pr={3}>
          <Ranking rankList={mockData} />
        </Box>
        <BottomNavigation
          showLabels
          sx={{
            maxWidth: 360,
            position: 'fixed',
            bottom: 0,
            left: 0,
            right: 0,
          }}
        >
          <BottomNavigationAction label="Recents" icon={<RestoreIcon />} />
          <BottomNavigationAction label="Favorites" icon={<FavoriteIcon />} />
          <BottomNavigationAction label="Nearby" icon={<LocationOnIcon />} />
        </BottomNavigation>
      </Box>
    </>
  );
};

const mockData = [
  {
    problemRank: 1,
    problem: '안녕하세요',
    successRate: 30,
  },
  {
    problemRank: 2,
    problem: '반갑습니다',
    successRate: 40,
  },
  {
    problemRank: 3,
    problem: 'LT-Group입니다',
    successRate: 50,
  },
  {
    problemRank: 1,
    problem: '안녕하세요',
    successRate: 30,
  },
  {
    problemRank: 2,
    problem: '반갑습니다',
    successRate: 40,
  },
  {
    problemRank: 3,
    problem: 'LT-Group입니다',
    successRate: 50,
  },
  {
    problemRank: 1,
    problem: '안녕하세요',
    successRate: 30,
  },
  {
    problemRank: 2,
    problem: '반갑습니다',
    successRate: 40,
  },
  {
    problemRank: 3,
    problem: 'LT-Group입니다',
    successRate: 50,
  },
];

export default RankingPage;
